version: 2

project_name: snapdev

builds:
  - id: snapdev
    main: ./main.go          
    binary: snapdev
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/orislabsdev/snapdev/cmd.Version={{.Version}}
      - -X github.com/orislabsdev/snapdev/cmd.Commit={{.Commit}}
      - -X github.com/orislabsdev/snapdev/cmd.BuildDate={{.Date}}

archives:
  - id: default
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats: [zip]
    name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ with .Arm }}v{{ . }}{{ end }}'

checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_checksums.txt'
  algorithm: sha256

snapshot:
  version_template: "{{ .Tag }}-snapshot"

release:
  github:
    owner: orislabsdev     
    # name: snapdev               
  draft: false
  prerelease: auto
  disable: true